<script lang="ts">
 import { goto } from '$app/navigation'; import { onMount } from 'svelte'; import { getBackendUrl } from '$lib/config'; import { readLanguagePreference } from '$lib/languagePreferences';
 let language: 'en'|'es'|'pt-BR'='en', displayName='', errorMessage='', saving=false;
 const copy={en:{title:'Complete your profile',intro:'Please choose a display name to continue.',label:'Display name',hint:'2–50 characters',save:'Save and continue',saving:'Saving...',invalid:'Enter a display name between 2 and 50 characters.',failed:'We could not save your display name. Please try again.'},es:{title:'Completa tu perfil',intro:'Elige un nombre para mostrar para continuar.',label:'Nombre para mostrar',hint:'De 2 a 50 caracteres',save:'Guardar y continuar',saving:'Guardando...',invalid:'Ingresa un nombre para mostrar de 2 a 50 caracteres.',failed:'No pudimos guardar tu nombre. Intentalo de nuevo.'},'pt-BR':{title:'Complete seu perfil',intro:'Escolha um nome de exibicao para continuar.',label:'Nome de exibicao',hint:'De 2 a 50 caracteres',save:'Salvar e continuar',saving:'Salvando...',invalid:'Informe um nome de exibicao de 2 a 50 caracteres.',failed:'Nao foi possivel salvar seu nome. Tente novamente.'}} as const;
 $: text=copy[language]; onMount(()=>{const saved=readLanguagePreference();language=saved==='es'?'es':saved==='ptbr'?'pt-BR':'en';});
 async function submit(){const name=displayName.trim();errorMessage='';if(name.length<2||name.length>50){errorMessage=text.invalid;return;}saving=true;try{const r=await fetch(`${getBackendUrl()}/api/auth/profile-completion`,{method:'POST',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify({display_name:name})});if(!r.ok)throw new Error();await goto('/dashboard');}catch{errorMessage=text.failed;}finally{saving=false;}}
</script>
<main><section><h1>{text.title}</h1><p>{text.intro}</p><form on:submit|preventDefault={submit}><label for="display-name">{text.label}</label><input id="display-name" bind:value={displayName} minlength="2" maxlength="50" autocomplete="nickname" required disabled={saving}/><p>{text.hint}</p><button disabled={saving}>{saving?text.saving:text.save}</button></form>{#if errorMessage}<p role="alert">{errorMessage}</p>{/if}</section></main>
<style>main{min-height:100vh;display:grid;place-items:center;background:#121212;color:white;padding:1rem}section{width:min(430px,100%);padding:2rem;border-radius:1rem;background:#202020}form{display:grid;gap:.85rem}input,button{padding:.85rem;border-radius:.6rem;font-size:1rem}button{background:#1db954;color:white;border:0}</style>
