<script lang="ts">
    import {goto} from '$app/navigation';
    import {onMount} from 'svelte';
    import PublicJourneyHeader from '$lib/components/journey/PublicJourneyHeader.svelte';
    import {readStoredLanguagePreference} from '$lib/languagePreferences';
    import type {Language} from '$lib/types/playback';

    let language: Language = 'en';
    let hasLanguage = false;

    const copy = {
        en: {
            title: "Gary's Story | TopSpot40", description: 'Why Gary W. Steele created TopSpot40, and why music discovery still matters.', eyebrow: 'About TopSpot40', hero: "Gary's Story", subtitle: 'Why I created TopSpot40, and why music discovery still matters.', back: 'Back to Welcome',
            sections: [
                ['Growing Up with Radio', ["TopSpot40 began with memories of growing up on an Indiana farm, where radio was more than background noise. Programs like Casey Kasem’s American Top 40 did more than play songs. They created anticipation, told stories, introduced artists, and made music feel like a journey."]],
                ['The Story Behind the Name', ['People occasionally ask where the name TopSpot40 came from. The answer reflects the three major influences behind the project.', 'Top refers to the ranked music programs that form the foundation of TopSpot40. Like the countdown shows I enjoyed growing up, songs are organized into ranked lists that highlight memorable tracks from each decade, genre, or collection.', 'Spot is a nod to Spotify. TopSpot40 can open selected tracks in Spotify, while Spotify handles music playback, advertisements, availability, account restrictions, and Free or Premium behavior. TopSpot40 adds storytelling, artist biographies, music history, and discovery.', 'The number 40 comes from the influence of Casey Kasem’s American Top 40 countdowns. Those programs inspired my love of music rankings, artist stories, and the excitement of discovering what song would come next.', 'Put together, the name TopSpot40 represents ranked music discovery, direct Spotify links for listening, and the enduring influence of the Top 40 radio tradition that inspired the project.', 'I wanted to bring some of that feeling back. Streaming services make it easy to hear almost any song instantly, but the stories behind the songs are often missing. TopSpot40 was created to add the context, history, artist information, and storytelling that make music more meaningful.']],
                ['Music, Memory, and Older Generations', ['One of my hopes for TopSpot40 is that it can help older generations reconnect with the songs that shaped their lives. A favorite song can bring back memories of childhood, first dates, military service, weddings, family gatherings, church, road trips, and moments that might otherwise have faded.', 'Music has a special ability to connect people across generations. TopSpot40 is my way of honoring those memories while helping younger listeners discover the music, artists, and stories that came before them.']],
                ["Patty's Rule", ['My wife Patty has played an important role in shaping TopSpot40 from the very beginning. Fluent in English, Spanish, and Portuguese, she brought a unique perspective to the project as both a music lover and a multilingual listener.', 'Over time, I developed what I jokingly call “Patty’s Rule”: if Patty cannot easily understand or enjoy a feature, it probably needs to be simplified. That simple principle helped keep TopSpot40 focused on the listener rather than the technology. As an engineer, I naturally enjoy building systems and adding features, but Patty consistently reminded me that the experience should remain intuitive, enjoyable, and accessible.', 'Patty also played a vital role in one of the most distinctive parts of TopSpot40—its narrated storytelling. As we explored the growing library of ElevenLabs voices, she helped evaluate and select many of the voices used throughout the platform. Her fluency in all three supported languages allowed her to judge pronunciation, pacing, tone, and overall authenticity in ways that I could not have done alone.', 'The result is that TopSpot40 does not simply tell stories in English, Spanish, and Portuguese—it tells them in voices carefully chosen to sound natural and engaging to listeners in each language. Many of the voices heard throughout the platform were selected with Patty’s guidance and encouragement.', 'In many ways, Patty helped shape not only how TopSpot40 works, but also how it sounds.'], 'Patty’s Rule: If a feature is too complicated to enjoy, it probably needs to be simplified.'],
                ['Teaching, Isaiah, and the Python Class', ['TopSpot40 also grew out of my work with the Pharr Fetched Coders group at the Pharr Memorial Library. What started as a local Python programming class became connected to a real software project.', 'Through that group, I met Isaiah, a computer science student at the University of Texas Rio Grande Valley. Working with him reminded me that learning is a two-way street. I have been able to share decades of experience in programming, engineering, and project development, while Isaiah has brought fresh ideas, modern web development skills, and a new perspective to the platform.']],
                ['Music Without Borders', ['My life and career have also shaped the multilingual side of TopSpot40. I am bilingual in English and Spanish, and somewhat fluent in Portuguese after working in Angola, Africa as a Six Sigma consultant. Those experiences expanded my appreciation for the ways music connects people across languages and cultures.', 'That is one reason TopSpot40 supports English, Spanish, and Portuguese. Music may be a universal language, but I wanted the stories behind the music to be accessible too.']],
                ['A Personal Journey', ['What began as a software project gradually became something much more personal. Along the way, TopSpot40 introduced me to artists, stories, cultures, and musical traditions that I might never have explored otherwise.', 'In that sense, TopSpot40 has been almost a spiritual journey for me. It has deepened my appreciation for music, history, heritage, creativity, and the experiences that connect us across generations.']],
                ['Discovery Never Ends', ['One of my favorite discoveries came from my own project. While exploring music and artists for TopSpot40, I came across B.B. King and realized I knew very little about him, despite his enormous influence on blues and popular music.', 'That discovery led me to learn about his remarkable career, his influence on generations of musicians, and his connection to artists such as Buddy Guy. In fact, learning through TopSpot40 inspired me to plan a trip to see Buddy Guy perform in person.', 'If TopSpot40 has taught me anything, it is that discovery never ends. There is always another artist to learn about, another story to hear, another culture to appreciate, and another song waiting to become a favorite.']]
            ], open: 'Read this section', close: 'Hide this section'
        },
        es: {
            title: 'La historia de Gary | TopSpot40', description: 'Por qué Gary W. Steele creó TopSpot40 y por qué el descubrimiento musical sigue siendo importante.', eyebrow: 'Acerca de TopSpot40', hero: 'La historia de Gary', subtitle: 'Por qué creé TopSpot40 y por qué el descubrimiento musical sigue siendo importante.', back: 'Volver a Bienvenida',
            sections: [
                ['Crecer con la radio', ['TopSpot40 comenzó con recuerdos de crecer en una granja de Indiana, donde la radio era más que ruido de fondo. Programas como American Top 40 de Casey Kasem hacían más que reproducir canciones. Creaban expectación, contaban historias, presentaban artistas y hacían que la música se sintiera como un viaje.']],
                ['La historia detrás del nombre', ['A veces me preguntan de dónde viene el nombre TopSpot40. La respuesta refleja las tres influencias principales detrás del proyecto.', 'Top se refiere a los programas musicales clasificados que forman la base de TopSpot40. Como los programas de cuenta regresiva que disfrutaba al crecer, las canciones se organizan en listas clasificadas que destacan temas memorables de cada década, género o colección.', 'Spot es un guiño a Spotify. TopSpot40 puede abrir canciones seleccionadas en Spotify, mientras Spotify gestiona la reproducción, los anuncios, la disponibilidad, las restricciones de cuenta y el funcionamiento de Free o Premium. TopSpot40 añade narración, biografías de artistas, historia de la música y descubrimiento.', 'El número 40 proviene de la influencia de las cuentas regresivas American Top 40 de Casey Kasem. Esos programas inspiraron mi amor por las clasificaciones musicales, las historias de artistas y la emoción de descubrir qué canción vendría después.', 'Junto, el nombre TopSpot40 representa el descubrimiento musical clasificado, enlaces directos a Spotify para escuchar y la influencia perdurable de la tradición radiofónica del Top 40 que inspiró el proyecto.', 'Quise recuperar parte de esa sensación. Los servicios de streaming facilitan escuchar casi cualquier canción al instante, pero a menudo faltan las historias detrás de las canciones. TopSpot40 fue creado para añadir el contexto, la historia, la información sobre artistas y la narración que hacen que la música sea más significativa.']],
                ['Música, memoria y generaciones mayores', ['Una de mis esperanzas para TopSpot40 es que pueda ayudar a las generaciones mayores a reconectarse con las canciones que marcaron sus vidas. Una canción favorita puede traer recuerdos de la infancia, primeras citas, servicio militar, bodas, reuniones familiares, iglesia, viajes por carretera y momentos que de otro modo podrían haberse desvanecido.', 'La música tiene una capacidad especial para conectar a las personas entre generaciones. TopSpot40 es mi manera de honrar esos recuerdos y, al mismo tiempo, ayudar a los oyentes más jóvenes a descubrir la música, los artistas y las historias que los precedieron.']],
                ["La regla de Patty", ['Mi esposa Patty ha desempeñado un papel importante en la formación de TopSpot40 desde el principio. Con dominio del inglés, español y portugués, aportó una perspectiva única al proyecto como amante de la música y oyente multilingüe.', 'Con el tiempo desarrollé lo que en broma llamo “la regla de Patty”: si Patty no puede entender o disfrutar fácilmente una función, probablemente hay que simplificarla. Ese principio sencillo ayudó a mantener a TopSpot40 centrado en el oyente y no en la tecnología. Como ingeniero, naturalmente disfruto construir sistemas y añadir funciones, pero Patty me recordaba constantemente que la experiencia debía seguir siendo intuitiva, agradable y accesible.', 'Patty también desempeñó un papel vital en una de las partes más distintivas de TopSpot40: su narración con voces. Mientras explorábamos la creciente biblioteca de voces de ElevenLabs, ayudó a evaluar y seleccionar muchas de las voces que se usan en toda la plataforma. Su dominio de los tres idiomas compatibles le permitió evaluar la pronunciación, el ritmo, el tono y la autenticidad general de maneras que yo no podría haber logrado solo.', 'El resultado es que TopSpot40 no solo cuenta historias en inglés, español y portugués: las cuenta con voces cuidadosamente elegidas para sonar naturales y atractivas para los oyentes de cada idioma. Muchas de las voces que se escuchan en la plataforma fueron seleccionadas con la guía y el ánimo de Patty.', 'En muchos sentidos, Patty ayudó a dar forma no solo a cómo funciona TopSpot40, sino también a cómo suena.'], 'La regla de Patty: Si una función es demasiado complicada para disfrutarla, probablemente hay que simplificarla.'],
                ['Enseñanza, Isaiah y la clase de Python', ['TopSpot40 también surgió de mi trabajo con el grupo Pharr Fetched Coders en la Biblioteca Memorial de Pharr. Lo que comenzó como una clase local de programación en Python llegó a conectarse con un proyecto de software real.', 'A través de ese grupo conocí a Isaiah, estudiante de ciencias de la computación en la Universidad de Texas Rio Grande Valley. Trabajar con él me recordó que aprender es una calle de doble sentido. He podido compartir décadas de experiencia en programación, ingeniería y desarrollo de proyectos, mientras Isaiah ha aportado ideas nuevas, habilidades modernas de desarrollo web y una nueva perspectiva a la plataforma.']],
                ['Música sin fronteras', ['Mi vida y mi carrera también han dado forma al lado multilingüe de TopSpot40. Soy bilingüe en inglés y español, y tengo cierta fluidez en portugués después de trabajar en Angola, África, como consultor Six Sigma. Esas experiencias ampliaron mi aprecio por las maneras en que la música conecta a las personas entre idiomas y culturas.', 'Esa es una razón por la que TopSpot40 admite inglés, español y portugués. La música puede ser un idioma universal, pero también quería que las historias detrás de ella fueran accesibles.']],
                ['Un viaje personal', ['Lo que comenzó como un proyecto de software gradualmente se convirtió en algo mucho más personal. En el camino, TopSpot40 me presentó artistas, historias, culturas y tradiciones musicales que quizá nunca habría explorado de otra manera.', 'En ese sentido, TopSpot40 ha sido casi un viaje espiritual para mí. Ha profundizado mi aprecio por la música, la historia, el patrimonio, la creatividad y las experiencias que nos conectan entre generaciones.']],
                ['El descubrimiento nunca termina', ['Uno de mis descubrimientos favoritos surgió de mi propio proyecto. Mientras exploraba música y artistas para TopSpot40, encontré a B.B. King y me di cuenta de que sabía muy poco sobre él, a pesar de su enorme influencia en el blues y la música popular.', 'Ese descubrimiento me llevó a conocer su notable carrera, su influencia en generaciones de músicos y su conexión con artistas como Buddy Guy. De hecho, aprender a través de TopSpot40 me inspiró a planear un viaje para ver a Buddy Guy actuar en persona.', 'Si TopSpot40 me ha enseñado algo, es que el descubrimiento nunca termina. Siempre hay otro artista por conocer, otra historia por escuchar, otra cultura por apreciar y otra canción esperando convertirse en una favorita.']]
            ], open: 'Leer esta sección', close: 'Ocultar esta sección'
        },
        ptbr: {
            title: 'A história de Gary | TopSpot40', description: 'Por que Gary W. Steele criou o TopSpot40 e por que a descoberta musical continua importante.', eyebrow: 'Sobre o TopSpot40', hero: 'A história de Gary', subtitle: 'Por que criei o TopSpot40 e por que a descoberta musical continua importante.', back: 'Voltar às boas-vindas',
            sections: [
                ['Crescendo com o rádio', ['O TopSpot40 começou com lembranças de crescer em uma fazenda em Indiana, onde o rádio era mais do que som de fundo. Programas como o American Top 40 de Casey Kasem faziam mais do que tocar músicas. Eles criavam expectativa, contavam histórias, apresentavam artistas e faziam a música parecer uma jornada.']],
                ['A história por trás do nome', ['Às vezes as pessoas me perguntam de onde veio o nome TopSpot40. A resposta reflete as três maiores influências por trás do projeto.', 'Top refere-se aos programas musicais classificados que formam a base do TopSpot40. Como os programas de contagem regressiva de que eu gostava ao crescer, as músicas são organizadas em listas classificadas que destacam faixas memoráveis de cada década, gênero ou coleção.', 'Spot é uma referência ao Spotify. O TopSpot40 pode abrir faixas selecionadas no Spotify, enquanto o Spotify cuida da reprodução musical, dos anúncios, da disponibilidade, das restrições de conta e do funcionamento do Free ou Premium. O TopSpot40 acrescenta narrativas, biografias de artistas, história da música e descoberta.', 'O número 40 vem da influência das contagens regressivas do American Top 40 de Casey Kasem. Esses programas inspiraram meu amor por classificações musicais, histórias de artistas e a emoção de descobrir qual música viria em seguida.', 'Junto, o nome TopSpot40 representa descoberta musical classificada, links diretos para ouvir no Spotify e a influência duradoura da tradição radiofônica do Top 40 que inspirou o projeto.', 'Eu queria trazer de volta parte dessa sensação. Serviços de streaming facilitam ouvir quase qualquer música instantaneamente, mas as histórias por trás das músicas muitas vezes estão ausentes. O TopSpot40 foi criado para acrescentar o contexto, a história, as informações sobre artistas e as narrativas que tornam a música mais significativa.']],
                ['Música, memória e gerações mais velhas', ['Uma das minhas esperanças para o TopSpot40 é que ele possa ajudar as gerações mais velhas a se reconectarem com as músicas que moldaram suas vidas. Uma música favorita pode trazer de volta memórias da infância, primeiros encontros, serviço militar, casamentos, reuniões de família, igreja, viagens de carro e momentos que, de outra forma, poderiam ter se apagado.', 'A música tem uma capacidade especial de conectar pessoas entre gerações. O TopSpot40 é a minha maneira de honrar essas memórias e, ao mesmo tempo, ajudar ouvintes mais jovens a descobrir a música, os artistas e as histórias que vieram antes deles.']],
                ['A regra de Patty', ['Minha esposa Patty desempenhou um papel importante na formação do TopSpot40 desde o começo. Fluente em inglês, espanhol e português, ela trouxe uma perspectiva única ao projeto como amante da música e ouvinte multilíngue.', 'Com o tempo, desenvolvi o que, brincando, chamo de “a regra de Patty”: se Patty não consegue entender ou aproveitar um recurso facilmente, provavelmente ele precisa ser simplificado. Esse princípio simples ajudou a manter o TopSpot40 focado no ouvinte, e não na tecnologia. Como engenheiro, naturalmente gosto de construir sistemas e acrescentar recursos, mas Patty me lembrava constantemente que a experiência deveria permanecer intuitiva, agradável e acessível.', 'Patty também teve um papel vital em uma das partes mais marcantes do TopSpot40 — suas narrativas com voz. Enquanto explorávamos a crescente biblioteca de vozes da ElevenLabs, ela ajudou a avaliar e selecionar muitas das vozes usadas em toda a plataforma. Sua fluência nos três idiomas compatíveis permitiu que ela avaliasse pronúncia, ritmo, tom e autenticidade geral de maneiras que eu não conseguiria sozinho.', 'O resultado é que o TopSpot40 não apenas conta histórias em inglês, espanhol e português — ele as conta com vozes cuidadosamente escolhidas para soar naturais e envolventes para os ouvintes de cada idioma. Muitas das vozes ouvidas na plataforma foram selecionadas com a orientação e o incentivo de Patty.', 'De muitas maneiras, Patty ajudou a moldar não apenas como o TopSpot40 funciona, mas também como ele soa.'], 'A regra de Patty: Se um recurso é complicado demais para ser aproveitado, provavelmente ele precisa ser simplificado.'],
                ['Ensino, Isaiah e a aula de Python', ['O TopSpot40 também cresceu a partir do meu trabalho com o grupo Pharr Fetched Coders, da Biblioteca Memorial de Pharr. O que começou como uma aula local de programação em Python acabou se conectando a um projeto de software real.', 'Por meio desse grupo, conheci Isaiah, estudante de ciência da computação da University of Texas Rio Grande Valley. Trabalhar com ele me lembrou que aprender é uma via de mão dupla. Pude compartilhar décadas de experiência em programação, engenharia e desenvolvimento de projetos, enquanto Isaiah trouxe ideias novas, habilidades modernas de desenvolvimento web e uma nova perspectiva para a plataforma.']],
                ['Música sem fronteiras', ['Minha vida e minha carreira também moldaram o lado multilíngue do TopSpot40. Sou bilíngue em inglês e espanhol, e tenho alguma fluência em português depois de trabalhar em Angola, na África, como consultor Six Sigma. Essas experiências ampliaram minha apreciação pelas maneiras como a música conecta as pessoas entre idiomas e culturas.', 'Essa é uma das razões pelas quais o TopSpot40 oferece suporte a inglês, espanhol e português. A música pode ser uma língua universal, mas eu também queria que as histórias por trás dela fossem acessíveis.']],
                ['Uma jornada pessoal', ['O que começou como um projeto de software gradualmente se tornou algo muito mais pessoal. Ao longo do caminho, o TopSpot40 me apresentou artistas, histórias, culturas e tradições musicais que talvez eu nunca tivesse explorado de outra forma.', 'Nesse sentido, o TopSpot40 tem sido quase uma jornada espiritual para mim. Ele aprofundou minha apreciação pela música, história, herança, criatividade e pelas experiências que nos conectam entre gerações.']],
                ['A descoberta nunca termina', ['Uma das minhas descobertas favoritas veio do meu próprio projeto. Enquanto explorava música e artistas para o TopSpot40, encontrei B.B. King e percebi que sabia muito pouco sobre ele, apesar de sua enorme influência no blues e na música popular.', 'Essa descoberta me levou a conhecer sua carreira notável, sua influência sobre gerações de músicos e sua conexão com artistas como Buddy Guy. Na verdade, aprender por meio do TopSpot40 me inspirou a planejar uma viagem para ver Buddy Guy se apresentar pessoalmente.', 'Se o TopSpot40 me ensinou algo, é que a descoberta nunca termina. Sempre há outro artista para conhecer, outra história para ouvir, outra cultura para apreciar e outra música esperando para se tornar favorita.']]
            ], open: 'Leia esta seção', close: 'Ocultar esta seção'
        }
    } as const;

    onMount(() => { const savedLanguage = readStoredLanguagePreference(); if (!savedLanguage) { void goto('/journey-prototype', {replaceState: true}); return; } language = savedLanguage; hasLanguage = true; });
</script>

<svelte:head><title>{copy[language].title}</title><meta name="description" content={copy[language].description}/></svelte:head>

{#if hasLanguage}
    <div class="story-page"><PublicJourneyHeader {language}/><main><a class="back" href="/welcome">← {copy[language].back}</a><header><p class="eyebrow">{copy[language].eyebrow}</p><h1>{copy[language].hero}</h1><p class="subtitle">{copy[language].subtitle}</p></header><div class="story"><section><h2>{copy[language].sections[0][0]}</h2>{#each copy[language].sections[0][1] as paragraph}<p>{paragraph}</p>{/each}</section>{#each copy[language].sections.slice(1) as section}<details><summary>{section[0]}</summary><div class="detail-content">{#each section[1] as paragraph}<p>{paragraph}</p>{/each}{#if section[2]}<blockquote>{section[2]}</blockquote>{/if}</div></details>{/each}</div><footer><a class="back" href="/welcome">← {copy[language].back}</a></footer></main></div>
{/if}

<style>
    :global(html), :global(body) { margin: 0; background: #0b0a07; } :global(*) { box-sizing: border-box; } .story-page { min-height: 100vh; color: #fff4dd; background: radial-gradient(circle at 15% 0%, #34200f, #0b0a07 45rem); font-family: Arial, sans-serif; } main { width: min(980px, 100%); margin: auto; padding: clamp(26px, 5vw, 58px) clamp(18px, 4vw, 40px) 64px; } .back { display: inline-flex; align-items: center; min-height: 46px; padding: 10px 16px; color: #161108; background: #f5d66e; border: 2px solid #f7dc82; border-radius: 999px; font-weight: 800; text-decoration: none; } header { margin: 40px 0; } .eyebrow { color: #f5d66e; font-size: .85rem; font-weight: 800; letter-spacing: .13em; text-transform: uppercase; } h1, h2, summary { font-family: Georgia, serif; } h1 { margin: 0 0 16px; color: #f7dc82; font-size: clamp(2.5rem, 7vw, 5rem); line-height: 1.04; } .subtitle { max-width: 700px; font-size: clamp(1.15rem, 2vw, 1.45rem); } h2 { margin: 0 0 18px; color: #f7dc82; font-size: clamp(1.7rem, 4vw, 2.6rem); line-height: 1.15; } p { margin: 0 0 20px; color: #f6efe0; font-size: clamp(1.06rem, 1.8vw, 1.2rem); line-height: 1.7; } .story > section, details { padding: clamp(22px, 4vw, 36px); background: linear-gradient(145deg, rgba(48, 34, 16, .94), rgba(22, 18, 12, .96)); border: 1px solid rgba(245, 214, 110, .38); border-radius: 18px; } details { margin-top: 14px; background: #19140e; } summary { color: #fff4d1; cursor: pointer; font-size: clamp(1.32rem, 3vw, 1.75rem); font-weight: 800; line-height: 1.3; } .detail-content { padding-top: 24px; } .detail-content p:last-of-type, .story > section p:last-child { margin-bottom: 0; } blockquote { margin: 26px 0 0; padding: 18px 20px; color: #f7dc82; background: #0f0d09; border-left: 5px solid #d9aa28; font: italic 1.15rem/1.55 Georgia, serif; } footer { margin-top: 42px; text-align: center; } a:focus-visible, summary:focus-visible { outline: 3px solid #fff; outline-offset: 4px; } @media (max-width: 440px) { main { padding-inline: 14px; } .story > section, details { padding: 20px; } .back { width: 100%; justify-content: center; text-align: center; } } @media (prefers-reduced-motion: reduce) { *, *::before, *::after { scroll-behavior: auto !important; transition-duration: .01ms !important; animation-duration: .01ms !important; } }
</style>
